n = int(input('Пишите любой номер чтобы увидеть его таблицы умножения: '))
print('Таблица умножения')
print('-'*15)
print(f'{n} x 1 = {n}')
print(f'{n} x 2 = {n*2}')
print(f'{n} x 3 = {n*3}')
print(f'{n} x 4 = {n*4}')
print(f'{n} x 5 = {n*5}')
print(f'{n} x 6 = {n*6}')
print(f'{n} x 7 = {n*7}')
print(f'{n} x 8 = {n*8}')
print(f'{n} x 9 = {n*9}')
print('-'*15)

print('Молодец')